[package]
name = "tauri-plugin-leap-ai"
version = "0.1.1"
authors = [ "You" ]
description = ""
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-leap-ai"

[dependencies]
tauri = { version = "2.10.0" }
serde = "1.0"
thiserror = "2"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream"] }
futures-util = "0.3"
serde_json = "1.0"
sha2 = "0.10"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
llama-cpp-2 = { version = "0.1.133", default-features = false, optional = true }

[features]
default = []
desktop-embedded-llama = ["dep:llama-cpp-2"]

[build-dependencies]
tauri-plugin = { version = "2.5.3", features = ["build"] }

[dev-dependencies]
tempfile = "3"

[patch.crates-io]
swift-rs = { path = "vendor/swift-rs-leap" }
